<#assign
	backgroundColor1 = getterUtil.getString(themeDisplay.getThemeSetting("background-color-1"))
	backgroundColor2 = getterUtil.getString(themeDisplay.getThemeSetting("background-color-2"))
	backgroundGradientDirection = getterUtil.getString(themeDisplay.getThemeSetting("background-gradient-direction"))
	colorScheme = getterUtil.getString(themeDisplay.getColorSchemeId())
	dribbble = getterUtil.getBoolean(themeDisplay.getThemeSetting("dribbble"))
	dribbbleUrl = getterUtil.getString(themeDisplay.getThemeSetting("dribbble-url"))
	email = getterUtil.getString(themeDisplay.getThemeSetting("email"))
	facebook = getterUtil.getBoolean(themeDisplay.getThemeSetting("facebook"))
	facebookUrl = getterUtil.getString(themeDisplay.getThemeSetting("facebook-url"))
	github = getterUtil.getBoolean(themeDisplay.getThemeSetting("github"))
	githubUrl = getterUtil.getString(themeDisplay.getThemeSetting("github-url"))
	instagram = getterUtil.getBoolean(themeDisplay.getThemeSetting("instagram"))
	instagramUrl = getterUtil.getString(themeDisplay.getThemeSetting("instagram-url"))
	linkedin = getterUtil.getBoolean(themeDisplay.getThemeSetting("linkedin"))
	linkedinUrl = getterUtil.getString(themeDisplay.getThemeSetting("linkedin-url"))
	logoSize = getterUtil.getString(themeDisplay.getThemeSetting("logo-size"))
	phone = getterUtil.getString(themeDisplay.getThemeSetting("phone"))
	showAttributionInfo = getterUtil.getBoolean(themeDisplay.getThemeSetting("show-attribution-info"))
	showContactInfo = getterUtil.getBoolean(themeDisplay.getThemeSetting
	("show-contact-info"))
	showCopyrightInfo = getterUtil.getBoolean(themeDisplay.getThemeSetting("show-copyright-info"))
	showLanguagePicker = getterUtil.getBoolean(themeDisplay.getThemeSetting("show-language-picker"))
	showLogoImage = getterUtil.getBoolean(themeDisplay.getThemeSetting("show-logo-image"))
	showPortletBorders = getterUtil.getBoolean(themeDisplay.getThemeSetting("portlet-setup-show-borders-default"))
	twitter = getterUtil.getBoolean(themeDisplay.getThemeSetting("twitter"))
	twitterUrl = getterUtil.getString(themeDisplay.getThemeSetting("twitter-url"))
	year = .now
	youtube = getterUtil.getBoolean(themeDisplay.getThemeSetting("youtube"))
	youtubeUrl = getterUtil.getString(themeDisplay.getThemeSetting("youtube-url"))
/>
